# Theory Questions

1.What are the data structure and why its important ?
  - A data structure is a way of storing and organizing data in a computer so it can be accessed and manipulated  efficiently
  eg=list,dictionary,arrays
  Importance=efficient data handling,code organistaion,problem solving,built in support

2.Explain the difference between mutable and immutable data types with eg ?
  - Mutable- It can be updated modify after creation
  eg=list,dictionary,set
  - Immutable- It cant be updated or manipulated after creation
  eg=int,float,str,tuple

3.What are the main differences between lists and tuples in Python ?
  - List is mutable and tuple is immutable
 list denoted by [] and tuple denoted by ()

4.Describe how dictionaries store data ?
  - Dictionary stores data in key:value pair

5.Why might you use a set instead of a list in Python ?
  - use set when need unique element and mathematcal operation is required

6.What is a string in Python, and how is it different from a list ?
  - string is a sequence of character and its immuatble

7.How do tuples ensure data integrity in Python?
  - Tuples in Python ensure data integrity through their immutability which means once a tuple is created, its content cannot be changed. This property is valuable for scenarios where maintaining consistent unaltered data is essential.

8.What is a hash table, and how does it relate to dictionaries in Python ?
 - A hash table is a data structure that stores key-value pairs. It uses a hash function to compute an index (or hash code) for each key mapping it to a specific bucket or slot in memory. This allows for efficient operations like insertion deletion and lookup with an average time complexity of O(1)

9.Can lists contain different data types in Python?
  - Yes list contain different data types eg str,float,bool,int

10.Why strings are immutable in python
  - Strings are immutable in Python to ensure thread safety, memory efficiency, and reliable behavior when used as hashable keys in data structures like dictionaries and sets

11.What advantages do dictionaries offer over lists for certain tasks ?
  - Dictionaries offer faster lookups and efficient key-value pairing making them ideal for tasks that require quick access by keys or mapping relationships. Unlike lists, dictionaries provide O(1) average time complexity for lookups whereas lists require O(n) for searching elements

12.Describe a scenario where using a tuple would be preferable over a list?
   - A tuple would be preferable over a list in a scenario where you need to store a fixed collection of related values such as the coordinates of a location (latitude, longitude) and you want to ensure the data remains unchanged. Since tuples are immutable, they guarantee data integrity and can also be used as keys in dictionaries unlike lists.

13.How do sets handle duplicate values in Python?
   - Sets automatically eliminate duplicate values

14.How does the “in” keyword work differently for lists and dictionaries?
   - In list "in" check presence of value
     In Dict "in" check the presence of key

15.Can you modify the elements of a tuple? Explain why or why not?
   - Tuple is immutable so modification is not alowed

16.What is a nested dictionary, and give an example of its use case ?
   - A nested dictionary is a dictionary where the values are themselves dictionaries allowing hierarchical data representation
   students = {
    "Anand": {"age": 20, "grades": {"math": 90, "science": 85}},
    "Ajay": {"age": 22, "grades": {"math": 88, "science": 92}}
}

17.Describe the time complexity of accessing elements in a dictionary ?
   - The time complexity of accessing elements in a dictionary in Python is O(1) on average. This means that retrieving a value using a key takes constant time, regardless of the size of the dictionary.

18.In what situations are lists preferred over dictionaries ?
   - Lists are preferred over dictionaries when you need ordered data allow duplicates or require sequential access by index.

19.Why are dictionaries considered unordered, and how does that affect data
   retrieval ?
   - Dictionaries are considered unordered because their elements are stored based on hash values, not insertion order, which means the order of key-value pairs is not guaranteed

20.Explain the difference between a list and a dictionary in terms of data
   retrieval?
   - In list data is retrive through indexing
     In dict data is retrieve through key

# Practical questiions

In [ ]:
#1 Write a code to create a string with your name and print it
_name = "Anand"
print(_name)

Anand

In [ ]:
#2 Write a code to find the length of the string "Hello World"
messege = "Hello World"
print(len(messege))

11

In [ ]:
'''3 Write a code to slice the first 3 characters from the string "Python
Programming'''

language = "Python Programming"
print(language[0:3])

Pyt

In [ ]:
#4 Write a code to convert the string "hello" to uppercase
a = "hello"
a.upper()

'HELLO'

In [ ]:
'''5 Write a code to replace the word "apple" with "orange" in the string "I
 like apple'''
a = "I like apple"
print(a.replace("apple","orange"))

I like orange

In [ ]:
#6 Write a code to create a list with numbers 1 to 5 and print it
num_list = [1,2,3,4,5]
print(num_list)

[1, 2, 3, 4, 5]

In [ ]:
#7 Write a code to append the number 10 to the list [1, 2, 3, 4]
my_list = [1,2,3,4]
my_list.append(10)
my_list

[1, 2, 3, 4, 10]

In [ ]:
#8 Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]
my_list = [1,2,3,4,5]
my_list.pop(2)
my_list

[1, 2, 4, 5]

In [ ]:
#9 Write a code to access the second element in the list ['a', 'b', 'c', 'd']
apl_list = ['a', 'b', 'c', 'd']
apl_list[1]

'b'

In [ ]:
#10 Write a code to reverse the list [10, 20, 30, 40, 50]
my_list = [10, 20, 30, 40, 50]
my_list[::-1]

[50, 40, 30, 20, 10]

In [ ]:
#11 Write a code to create a tuple with the elements 10, 20, 30 and print it
my_tup = (10,20,30)
my_tup

(10, 20, 30)

In [ ]:
"""12 Write a code to access the first element of the tuple
('apple', 'banana', 'cherry')"""
fruits_list = ('apple', 'banana', 'cherry')
fruits_list[0]

'apple'

In [ ]:
"""13 Write a code to count how many times the number 2 appears in the tuple
(1, 2, 3, 2, 4, 2)"""
num_num = (1, 2, 3, 2, 4, 2)
num_num.count(2)

3

In [ ]:
"""14 Write a code to find the index of the element "cat" in the tuple
('dog', 'cat', 'rabbit')"""
tu_tu = ('dog', 'cat', 'rabbit')
tu_tu.index("cat")

1

In [ ]:
"""15 Write a code to check if the element "banana" is in the tuple
('apple', 'orange', 'banana')"""
my_ss = ('apple', 'orange', 'banana')
"banana" in my_ss

True

In [ ]:
#16.Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it
my_set = {1,2,3,4,5}
print(my_set)

{1, 2, 3, 4, 5}

In [ ]:
#17.Write a code to add the element 6 to the set {1, 2, 3, 4}.
my_set = {1,2,3,4}
my_set.add(6)
my_set

{1, 2, 3, 4, 6}

In [ ]:
#18.Write a code to create a tuple with the elements 10, 20, 30 and print it
my_tup = (10,20,30)
my_tup

(10, 20, 30)

In [ ]:
"""19.Write a code to access the first element of the tuple
('apple', 'banana', 'cherry')"""
fruits_list = ('apple', 'banana', 'cherry')
fruits_list[0]

'apple'

In [ ]:
"""20 Write a code to count how many times the number 2 appears in the tuple
(1, 2, 3, 2, 4, 2)"""
num_num = (1, 2, 3, 2, 4, 2)
num_num.count(2)

3

In [ ]:
"""21 Write a code to find the index of the element "cat" in the tuple
('dog', 'cat', 'rabbit')"""
tu_tu = ('dog', 'cat', 'rabbit')
tu_tu.index("cat")

1

In [ ]:
"""22 Write a code to check if the element "banana" is in the tuple
('apple', 'orange', 'banana')"""
my_ss = ('apple', 'orange', 'banana')
"banana" in my_ss

True

In [ ]:
#23.Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it
my_set = {1,2,3,4,5}
print(my_set)

{1, 2, 3, 4, 5}

In [ ]:
#24.Write a code to add the element 6 to the set {1, 2, 3, 4}
my_set = {1,2,3,4}
my_set.add(6)
my_set

{1, 2, 3, 4, 6}